version: '3.8'

services:
  database_happy:
    image: postgres
    container_name: database_happy
    restart: always
    ports:
      - 1605:5432
    environment:
      - POSTGRES_USER=moisesneto
      - POSTGRES_PASSWORD=tigadark
      - POSTGRES_DB=happy
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
